#开发板IO约束文件

#----------------------系统时钟---------------------------
#时钟周期约束
create_clock -period 10.000 -name sys_clk_p [get_ports sys_clk_p]
#时钟管脚
set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports sys_clk_p]
set_property IOSTANDARD DIFF_SSTL15_DCI [get_ports sys_clk_n]
set_property PACKAGE_PIN AE10 [get_ports sys_clk_p]
set_property PACKAGE_PIN AF10 [get_ports sys_clk_n]

#----------------------系统复位---------------------------
set_property -dict {PACKAGE_PIN AB25 IOSTANDARD LVCMOS33} [get_ports sys_rst_n]

#----------------------KEY---------------------------
set_property -dict {PACKAGE_PIN A26 IOSTANDARD LVCMOS33} [get_ports key[0]]
set_property -dict {PACKAGE_PIN A25 IOSTANDARD LVCMOS33} [get_ports key[1]]

#----------------------LED---------------------------
set_property -dict {PACKAGE_PIN R24 IOSTANDARD LVCMOS33} [get_ports {led[0]}]
set_property -dict {PACKAGE_PIN R23 IOSTANDARD LVCMOS33} [get_ports {led[1]}]

#----------------------BEEP---------------------------
set_property -dict {PACKAGE_PIN D28 IOSTANDARD LVCMOS33} [get_ports beep]

#----------------------UART---------------------------
set_property -dict {PACKAGE_PIN T23 IOSTANDARD LVCMOS33} [get_ports uart_rxd]
set_property -dict {PACKAGE_PIN T22 IOSTANDARD LVCMOS33} [get_ports uart_txd]

#----------------------IIC（EEPROM）----------------------
set_property -dict {PACKAGE_PIN C25 IOSTANDARD LVCMOS33} [get_ports iic_scl]
set_property -dict {PACKAGE_PIN B25 IOSTANDARD LVCMOS33} [get_ports iic_sda]

#----------------------LCD接口----------------------------
set_property -dict {PACKAGE_PIN T26 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[0]}]
set_property -dict {PACKAGE_PIN U29 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[1]}]
set_property -dict {PACKAGE_PIN T27 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[2]}]
set_property -dict {PACKAGE_PIN U30 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[3]}]
set_property -dict {PACKAGE_PIN T30 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[4]}]
set_property -dict {PACKAGE_PIN V26 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[5]}]
set_property -dict {PACKAGE_PIN R30 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[6]}]
set_property -dict {PACKAGE_PIN V27 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[7]}]
set_property -dict {PACKAGE_PIN P29 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[8]}]
set_property -dict {PACKAGE_PIN V22 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[9]}]
set_property -dict {PACKAGE_PIN R29 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[10]}]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[11]}]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[12]}]
set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[13]}]
set_property -dict {PACKAGE_PIN T21 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[14]}]
set_property -dict {PACKAGE_PIN V21 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[15]}]
set_property -dict {PACKAGE_PIN U24 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[16]}]
set_property -dict {PACKAGE_PIN W24 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[17]}]
set_property -dict {PACKAGE_PIN V24 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[18]}]
set_property -dict {PACKAGE_PIN W23 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[19]}]
set_property -dict {PACKAGE_PIN W21 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[20]}]
set_property -dict {PACKAGE_PIN T25 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[21]}]
set_property -dict {PACKAGE_PIN W22 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[22]}]
set_property -dict {PACKAGE_PIN U25 IOSTANDARD LVCMOS33} [get_ports {lcd_rgb[23]}]

set_property -dict {PACKAGE_PIN T28 IOSTANDARD LVCMOS33} [get_ports lcd_hs]
set_property -dict {PACKAGE_PIN R28 IOSTANDARD LVCMOS33} [get_ports lcd_vs]
set_property -dict {PACKAGE_PIN U28 IOSTANDARD LVCMOS33} [get_ports lcd_de]
set_property -dict {PACKAGE_PIN U27 IOSTANDARD LVCMOS33} [get_ports lcd_bl]
set_property -dict {PACKAGE_PIN R26 IOSTANDARD LVCMOS33} [get_ports lcd_pclk]
set_property -dict {PACKAGE_PIN P26 IOSTANDARD LVCMOS33} [get_ports lcd_rst]

#----------------------HDMI输入接口----------------------------
set_property PACKAGE_PIN E24 [get_ports iic_sda]
set_property PACKAGE_PIN D24 [get_ports iic_scl]

set_property PACKAGE_PIN B29 [get_ports video_vs_in]
set_property PACKAGE_PIN C29 [get_ports video_hs_in]
set_property PACKAGE_PIN A28 [get_ports video_de_in]
set_property PACKAGE_PIN D27 [get_ports video_clk_in]

set_property PACKAGE_PIN F25 [get_ports {video_rgb_in[23]}]
set_property PACKAGE_PIN E25 [get_ports {video_rgb_in[22]}]
set_property PACKAGE_PIN A30 [get_ports {video_rgb_in[21]}]
set_property PACKAGE_PIN B30 [get_ports {video_rgb_in[20]}]
set_property PACKAGE_PIN H26 [get_ports {video_rgb_in[19]}]
set_property PACKAGE_PIN H27 [get_ports {video_rgb_in[18]}]
set_property PACKAGE_PIN H30 [get_ports {video_rgb_in[17]}]
set_property PACKAGE_PIN G30 [get_ports {video_rgb_in[16]}]
set_property PACKAGE_PIN E26 [get_ports {video_rgb_in[15]}]
set_property PACKAGE_PIN F26 [get_ports {video_rgb_in[14]}]
set_property PACKAGE_PIN G29 [get_ports {video_rgb_in[13]}]
set_property PACKAGE_PIN F30 [get_ports {video_rgb_in[12]}]
set_property PACKAGE_PIN E30 [get_ports {video_rgb_in[11]}]
set_property PACKAGE_PIN D23 [get_ports {video_rgb_in[10]}]
set_property PACKAGE_PIN E23 [get_ports {video_rgb_in[9]}]
set_property PACKAGE_PIN B23 [get_ports {video_rgb_in[8]}]
set_property PACKAGE_PIN A23 [get_ports {video_rgb_in[7]}]
set_property PACKAGE_PIN H24 [get_ports {video_rgb_in[6]}]
set_property PACKAGE_PIN H25 [get_ports {video_rgb_in[5]}]
set_property PACKAGE_PIN G27 [get_ports {video_rgb_in[4]}]
set_property PACKAGE_PIN F27 [get_ports {video_rgb_in[3]}]
set_property PACKAGE_PIN F28 [get_ports {video_rgb_in[2]}]
set_property PACKAGE_PIN G28 [get_ports {video_rgb_in[1]}]
set_property PACKAGE_PIN B28 [get_ports {video_rgb_in[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_in[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports video_clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports video_de_in]
set_property IOSTANDARD LVCMOS33 [get_ports video_hs_in]
set_property IOSTANDARD LVCMOS33 [get_ports video_vs_in]

#------------------HDMI输出接口----------------------
set_property PACKAGE_PIN N19 [get_ports {video_rgb_out[23]}]
set_property PACKAGE_PIN N20 [get_ports {video_rgb_out[22]}]
set_property PACKAGE_PIN M29 [get_ports {video_rgb_out[21]}]
set_property PACKAGE_PIN M30 [get_ports {video_rgb_out[20]}]
set_property PACKAGE_PIN L22 [get_ports {video_rgb_out[19]}]
set_property PACKAGE_PIN L23 [get_ports {video_rgb_out[18]}]
set_property PACKAGE_PIN P23 [get_ports {video_rgb_out[17]}]
set_property PACKAGE_PIN N24 [get_ports {video_rgb_out[16]}]
set_property PACKAGE_PIN K23 [get_ports {video_rgb_out[15]}]
set_property PACKAGE_PIN K24 [get_ports {video_rgb_out[14]}]
set_property PACKAGE_PIN M22 [get_ports {video_rgb_out[13]}]
set_property PACKAGE_PIN M23 [get_ports {video_rgb_out[12]}]
set_property PACKAGE_PIN J27 [get_ports {video_rgb_out[11]}]
set_property PACKAGE_PIN J28 [get_ports {video_rgb_out[10]}]
set_property PACKAGE_PIN J29 [get_ports {video_rgb_out[9]}]
set_property PACKAGE_PIN H29 [get_ports {video_rgb_out[8]}]
set_property PACKAGE_PIN J26 [get_ports {video_rgb_out[7]}]
set_property PACKAGE_PIN K26 [get_ports {video_rgb_out[6]}]
set_property PACKAGE_PIN M28 [get_ports {video_rgb_out[5]}]
set_property PACKAGE_PIN L28 [get_ports {video_rgb_out[4]}]
set_property PACKAGE_PIN N25 [get_ports {video_rgb_out[3]}]
set_property PACKAGE_PIN N26 [get_ports {video_rgb_out[2]}]
set_property PACKAGE_PIN J23 [get_ports {video_rgb_out[1]}]
set_property PACKAGE_PIN J24 [get_ports {video_rgb_out[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {video_rgb_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports iic_scl]
set_property IOSTANDARD LVCMOS33 [get_ports iic_sda]

set_property IOSTANDARD LVCMOS33 [get_ports rstn_out]
set_property PACKAGE_PIN E29 [get_ports rstn_out]
set_property PACKAGE_PIN K28 [get_ports video_clk_out]
set_property PACKAGE_PIN P21 [get_ports video_de_out]
set_property PACKAGE_PIN P22 [get_ports video_hs_out]
set_property PACKAGE_PIN K29 [get_ports video_vs_out]

set_property IOSTANDARD LVCMOS33 [get_ports video_clk_out]
set_property IOSTANDARD LVCMOS33 [get_ports video_de_out]
set_property IOSTANDARD LVCMOS33 [get_ports video_hs_out]
set_property IOSTANDARD LVCMOS33 [get_ports video_vs_out]

#--------------------摄像头接口------------------------
create_clock -period 40.000 -name cmos_pclk [get_ports cam_pclk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cam_pclk_IBUF_inst/O]

set_property -dict {PACKAGE_PIN L26 IOSTANDARD LVCMOS33} [get_ports cam_pclk]
set_property -dict {PACKAGE_PIN N29 IOSTANDARD LVCMOS33} [get_ports cam_rst_n]
set_property -dict {PACKAGE_PIN N30 IOSTANDARD LVCMOS33} [get_ports cam_pwdn]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS33} [get_ports {cam_data[0]}]
set_property -dict {PACKAGE_PIN L20 IOSTANDARD LVCMOS33} [get_ports {cam_data[1]}]
set_property -dict {PACKAGE_PIN J21 IOSTANDARD LVCMOS33} [get_ports {cam_data[2]}]
set_property -dict {PACKAGE_PIN J22 IOSTANDARD LVCMOS33} [get_ports {cam_data[3]}]
set_property -dict {PACKAGE_PIN L30 IOSTANDARD LVCMOS33} [get_ports {cam_data[4]}]
set_property -dict {PACKAGE_PIN K30 IOSTANDARD LVCMOS33} [get_ports {cam_data[5]}]
set_property -dict {PACKAGE_PIN L21 IOSTANDARD LVCMOS33} [get_ports {cam_data[6]}]
set_property -dict {PACKAGE_PIN K21 IOSTANDARD LVCMOS33} [get_ports {cam_data[7]}]
set_property -dict {PACKAGE_PIN N27IOSTANDARD LVCMOS33} [get_ports cam_vsync]
set_property -dict {PACKAGE_PIN M27 IOSTANDARD LVCMOS33} [get_ports cam_href]
set_property -dict {PACKAGE_PIN M24 IOSTANDARD LVCMOS33} [get_ports cam_scl]
set_property -dict {PACKAGE_PIN M25 IOSTANDARD LVCMOS33} [get_ports cam_sda]
set_property PULLUP true [get_ports cam_scl]
set_property PULLUP true [get_ports cam_sda]

#-------------------双目摄像头接口-----------------------
create_clock -period 40.000 -name cmos_pclk [get_ports cam_pclk_1]
create_clock -period 40.000 -name cmos_pclk [get_ports cam_pclk_2]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {cam_pclk_1_IBUF_inst/O}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {cam_pclk_2_IBUF_inst/O}]
set_property -dict {PACKAGE_PIN C13 IOSTANDARD LVCMOS33} [get_ports cam_pclk_1]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVCMOS33} [get_ports cam_rst_n_1]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD LVCMOS33} [get_ports cam_pwdn_1]
set_property -dict {PACKAGE_PIN E15 IOSTANDARD LVCMOS33 } [get_ports {cam_data_1[0]}]
set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVCMOS33 } [get_ports {cam_data_1[1]}]
set_property -dict {PACKAGE_PIN E14 IOSTANDARD LVCMOS33 } [get_ports {cam_data_1[2]}]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVCMOS33 } [get_ports {cam_data_1[3]}]
set_property -dict {PACKAGE_PIN E13 IOSTANDARD LVCMOS33 } [get_ports {cam_data_1[4]}]
set_property -dict {PACKAGE_PIN B13 IOSTANDARD LVCMOS33 } [get_ports {cam_data_1[5]}]
set_property -dict {PACKAGE_PIN C14 IOSTANDARD LVCMOS33 } [get_ports {cam_data_1[6]}]
set_property -dict {PACKAGE_PIN A13 IOSTANDARD LVCMOS33 } [get_ports {cam_data_1[7]}]
set_property -dict {PACKAGE_PIN G14 IOSTANDARD LVCMOS33} [get_ports cam_vsync_1]
set_property -dict {PACKAGE_PIN G13 IOSTANDARD LVCMOS33} [get_ports cam_href_1]
set_property -dict {PACKAGE_PIN H13 IOSTANDARD LVCMOS33} [get_ports cam_scl_1]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS33} [get_ports cam_sda_1]
set_property PULLUP true [get_ports cam_scl_1]
set_property PULLUP true [get_ports cam_sda_1]

set_property -dict {PACKAGE_PIN D11 IOSTANDARD LVCMOS33} [get_ports cam_pclk_2]
set_property -dict {PACKAGE_PIN A11 IOSTANDARD LVCMOS33} [get_ports cam_rst_n_2]
set_property -dict {PACKAGE_PIN B14 IOSTANDARD LVCMOS33} [get_ports cam_pwdn_2]
set_property -dict {PACKAGE_PIN C12 IOSTANDARD LVCMOS33 } [get_ports {cam_data_2[0]}]
set_property -dict {PACKAGE_PIN C11 IOSTANDARD LVCMOS33 } [get_ports {cam_data_2[1]}]
set_property -dict {PACKAGE_PIN B11 IOSTANDARD LVCMOS33 } [get_ports {cam_data_2[2]}]
set_property -dict {PACKAGE_PIN B10 IOSTANDARD LVCMOS33 } [get_ports {cam_data_2[3]}]
set_property -dict {PACKAGE_PIN A10 IOSTANDARD LVCMOS33 } [get_ports {cam_data_2[4]}]
set_property -dict {PACKAGE_PIN E10 IOSTANDARD LVCMOS33 } [get_ports {cam_data_2[5]}]
set_property -dict {PACKAGE_PIN E12 IOSTANDARD LVCMOS33 } [get_ports {cam_data_2[6]}]
set_property -dict {PACKAGE_PIN D10 IOSTANDARD LVCMOS33 } [get_ports {cam_data_2[7]}]
set_property -dict {PACKAGE_PIN A15 IOSTANDARD LVCMOS33} [get_ports cam_vsync_2]
set_property -dict {PACKAGE_PIN A12 IOSTANDARD LVCMOS33} [get_ports cam_href_2]
set_property -dict {PACKAGE_PIN A14 IOSTANDARD LVCMOS33} [get_ports cam_scl_2]
set_property -dict {PACKAGE_PIN D12 IOSTANDARD LVCMOS33} [get_ports cam_sda_2]
set_property PULLUP true [get_ports cam_scl_2]
set_property PULLUP true [get_ports cam_sda_2]



#----------------------以太网---------------------------
create_clock -period 8.000 -name eth_rxc [get_ports eth_rxc]

set_property -dict {PACKAGE_PIN AD26 IOSTANDARD LVCMOS33} [get_ports eth_rst_n]
set_property -dict {PACKAGE_PIN AB27 IOSTANDARD LVCMOS33} [get_ports eth_rxc]
set_property -dict {PACKAGE_PIN AC27 IOSTANDARD LVCMOS33} [get_ports eth_rx_ctl]
set_property -dict {PACKAGE_PIN Y29 IOSTANDARD LVCMOS33} [get_ports {eth_rxd[0]}]
set_property -dict {PACKAGE_PIN W29 IOSTANDARD LVCMOS33} [get_ports {eth_rxd[1]}]
set_property -dict {PACKAGE_PIN AD28 IOSTANDARD LVCMOS33} [get_ports {eth_rxd[2]}]
set_property -dict {PACKAGE_PIN AD27 IOSTANDARD LVCMOS33} [get_ports {eth_rxd[3]}]

set_property -dict {PACKAGE_PIN AA27 IOSTANDARD LVCMOS33} [get_ports eth_txc]
set_property -dict {PACKAGE_PIN AB28 IOSTANDARD LVCMOS33} [get_ports eth_tx_ctl]
set_property -dict {PACKAGE_PIN AG30 IOSTANDARD LVCMOS33} [get_ports {eth_txd[0]}]
set_property -dict {PACKAGE_PIN AH30 IOSTANDARD LVCMOS33} [get_ports {eth_txd[1]}]
set_property -dict {PACKAGE_PIN AK30 IOSTANDARD LVCMOS33} [get_ports {eth_txd[2]}]
set_property -dict {PACKAGE_PIN AK29 IOSTANDARD LVCMOS33} [get_ports {eth_txd[3]}]


#----------------------SD卡---------------------------
set_property PACKAGE_PIN AC29 [get_ports sd_miso]
set_property IOSTANDARD LVCMOS33 [get_ports sd_miso]
set_property PACKAGE_PIN AB29 [get_ports sd_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports sd_mosi]
set_property PACKAGE_PIN Y30 [get_ports sd_cs]
set_property IOSTANDARD LVCMOS33 [get_ports sd_cs]
set_property PACKAGE_PIN AE30 [get_ports sd_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sd_clk]

#----------------------FLASH---------------------------
set_property PACKAGE_PIN U19 [get_ports spi_cs]
set_property PACKAGE_PIN R25 [get_ports spi_miso]
set_property PACKAGE_PIN P24 [get_ports spi_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports spi_cs]
set_property IOSTANDARD LVCMOS33 [get_ports spi_miso]
set_property IOSTANDARD LVCMOS33 [get_ports spi_mosi]

#----------------------RS485---------------------------
set_property -dict {PACKAGE_PIN U22 IOSTANDARD LVCMOS33} [get_ports rs485_uart_rxd]
set_property -dict {PACKAGE_PIN U23 IOSTANDARD LVCMOS33} [get_ports rs485_uart_txd]